x-name: whereisthegooglecar
version: "3.8"

services:
  bot:
    container_name: discord_bot
    build:
      context: ./bot
    volumes:
      - ./bot/:/bot
    environment:
      - TOKEN=${TOKEN}
      - GUILD_ID=${GUILD_ID}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_IP=${POSTGRES_IP}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_SERVERLESS_URL=${REDIS_SERVERLESS_URL}
      - REDIS_SERVERLESS_TOKEN=${REDIS_SERVERLESS_TOKEN}
      - AWS_SECRET_PUBLIC_KEY=${AWS_SECRET_PUBLIC_KEY}
      - AWS_SECRET_PRIVATE_KEY=${AWS_SECRET_PRIVATE_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
  db:
    container_name: database
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  redis-serverless:
    container_name: redis-serverless
    ports:
      - "${REDIS_SERVERLESS_PORT}:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${REDIS_SERVERLESS_TOKEN}
      SRH_CONNECTION_STRING: "redis://redis:6379"
