#!/bin/bash

# Check if the current branch is 'main'
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURRENT_BRANCH" != "main" ]; then
  echo "Not on 'main' branch. Skipping lint and deploy."
  exit 0
fi

# Check if there are changes in the 'site' folder
if ! git diff --quiet HEAD~1 HEAD -- site; then
  # Enter SITE directory
  SITE_PROJECT_PATH="site"
  cd "$SITE_PROJECT_PATH" || { echo "Failed to enter SITE directory"; exit 1; }

  # Run Lint
  bun run lint
  LINT_STATUS=$?

  # Go back to root
  cd - 

  exit 0
fi
