name = "whereisthegooglecar-api"
compatibility_date = "2023-12-01"
# compatibility_flags = [ "nodejs_compat" ]

node_compat = true

main = "src/index.ts"
route = "https://api.whereisthegooglecar.com/"
account_id = "29a550a82e84f3e21b02e0745aa303e5"

[vars]
PRISMA_CLIENT_FORCE_WASM=1
CORS_ORIGIN="https://www.whereisthegooglecar.com"
CSRF_ORIGIN="whereisthegooglecar.com"